name: Build and Run Hello World  
  
on:  
  push:  
    branches:  
      - main  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

        
      - name: Build Docker image  
        run: docker build -t 1410916941/helloworld .  
  
      - name: Run Docker container  
        run: docker run --rm 1410916941/helloworld
